# Deploy to Bunny.net on new push to master then invalidate the pull zone
# Credit 1: https://github.com/marketplace/actions/setup-node-js-environment
# Credit 2: https://github.com/marketplace/actions/bunnycdn-gh-action
# Credit 3: https://cmichel.medium.com/how-to-deploy-a-create-react-app-with-github-actions-5e01f7a7b6b

name: CI to Bunny.net Storage + CDN

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install

      - name: Generate files
        run: npm run build

      - name: Deploy to storage
        uses: Snider/bunnycdn-gh-action@v2.0.0
        with:
          source: "dist"
          storageZoneName: "sg-nuxt-bridge"
          accessKey: "${{ secrets.BUNNY_CDN_STORAGE_KEY }}"

      - name: Purge CDN cache
        uses: Snider/bunnycdn-gh-action@v2.0.0
        with:
          zoneId: "${{ secrets.BUNNY_CDN_PULL_ZONE_ID }}"
          zoneKey: "${{ secrets.BUNNY_CDN_ZONE_KEY }}"

      # THIS IS COMBINING BOTH DEPLOYING TO STORAGE AND PURGE PULL ZONE AS STEP
      # - name: Deploy to storage then purge cache (invalidate CDN)
      #   uses: Snider/bunnycdn-gh-action@v2.0.0
      #   with:
      #     source: "dist"
      #     storageZoneName: "sg-nuxt-bridge"
      #     accessKey: "${{ secrets.BUNNY_CDN_STORAGE_KEY }}"
      #     zoneId: "${{ secrets.BUNNY_CDN_PULL_ZONE_ID }}"
      #     zoneKey: "${{ secrets.BUNNY_CDN_ZONE_KEY }}"
