# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install
      - name: Generate files
        run: npm run build
      - name: Deploy to BunnyCDN > sg-nuxt-bridge
        uses: Snider/bunnycdn-gh-action@v2.0.0
        with:
          source: "dist"
          storageZoneName: "sg-nuxt-bridge"
          accessKey: "${{ secrets.BUNNY_CDN_STORAGE_KEY }}"
          zoneId: "${{ secrets.BUNNY_CDN_PULL_ZONE_ID }}"
          zoneKey: "${{ secrets.BUNNY_CDN_ZONE_KEY }}"
